CREATE TABLE CONTACT (
ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
FIRST_NAME VARCHAR(60) NOT NULL,
LAST_NAME VARCHAR(40) NOT NULL,
BIRTH_DATE DATE,
CONSTRAINT pk_concact PRIMARY KEY (ID),
CONSTRAINT uq_contact UNIQUE(FIRST_NAME, LAST_NAME)
);
CREATE TABLE CONTACT_TEL_DETAIL (
ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
CONTACT_ID INTEGER NOT NULL,
TEL_TYPE VARCHAR(20) NOT NULL,
TEL_NUMBER VARCHAR(20) NOT NULL,
CONSTRAINT pk_contact_tel_detail PRIMARY KEY (ID),
CONSTRAINT uq_contact_tel_detail UNIQUE(CONTACT_ID, TEL_TYPE),
CONSTRAINT fk_contact_tel_detail FOREIGN KEY(CONTACT_ID) REFERENCES CONTACT(ID)
);
